### ISSUE TITLE
和我的Solon项目好像：）

### ISSUE THREAD

**Issue by noear** [avaje/avaje-http#111]
相互关注下：

[https://github.com/noear/solon](https://github.com/noear/solon)

**Comment by SentryMan** [comment]
So is there a problem here?

**Comment by rbygrave** [comment]
I _think_ this is just saying that the projects are similar and that we should monitor each others projects.

The challenge for me is that I struggle to read the documentation for the other project.

**Comment by re-thc** [comment]
I don't see the similarities. 

This project specifically is based on annotation processors and is the selling point. It's not reflection based.

Solon is more comparable to Spring or Micronaut or Quarkus in being a full framework. This project only concerns the http api segment.

**Comment by rbygrave** [comment]
Well in that case we should probably just close this ticket because I don't see this avaje http project taking any action or adding documentation for this.

I have no problem if someone wants to add more comments and/or comparisons and re-open this ticket some time in the future.

I'll close this for now.
