### ISSUE TITLE
benchmark 

### ISSUE THREAD

**Issue by GeorgeSalu** [avaje/avaje-http#286]
Is there any benchmark comparing with other libs like openfeing

**Comment by SentryMan** [comment]
which part, http client?

**Comment by SentryMan** [comment]
avaje-http-client is nothing but a paper-thin wrapper on the built-in JDK `HttpClient` class. It doesn't make the HTTP calls faster or slower than regular. There are probably some benchmarks somewhere on the built-in class

**Comment by rob-bygrave** [comment]
> openfeing

As in https://github.com/OpenFeign/feign right?  

What I did do a number of years ago was benchmark the _JDK HttpClient_ versus _OkHttp_. I did this because I was looking to move my preference from my then preferred OkHttp to the JDK HttpClient. For myself, I got very comfortable with the performance of JDK HttpClient and since then it has been my preferred http client library.

This also lead to avaje-http-client being a _thin wrapper for JDK HttpClient_ and so unlike OpenFeign it really **_ONLY_** targets the JDK HttpClient.

IMO people will want to use OpenFeign if they want to or need to use another http client (not JDK HttpClient).

**Comment by GeorgeSalu** [comment]
I really liked the avaje-http-client api, there's one thing I didn't find in the avaje-http-client documentation, which would be how to map a return error object from a get query, for example

**Comment by SentryMan** [comment]
> how to map a return error object from a get query, for example

here you go: https://avaje.io/http-client/#httpException

**Comment by rob-bygrave** [comment]
We should improve the docs in that we now have:

`HttpClient.Builder. globalErrorMapper()`
https://github.com/avaje/avaje-http/blob/master/http-client/src/main/java/io/avaje/http/client/HttpClient.java#L133

`HttpClientRequest errorMapper()`
https://github.com/avaje/avaje-http/blob/master/http-client/src/main/java/io/avaje/http/client/HttpClientRequest.java#L401

... for folks to register a customer error handler to convert HttpException into an application specific RuntimeException.

Plus, with the http client code generation, if a method throws a custom exception that has a constructor that takes a HttpException, then the generated code will automatically register that as a error handler.

----
I feel like there could be cases in the http client api code generation, where it might be useful to support 2 other maybe common cases:
1. application exceptions that only take int statusCode and String message body
2. two application exceptions with one specifically for 422 validation errors with known body type and all other errors (500s etc) 

Currently we would register a error handler `Function<HttpException, RuntimeException>` to handle this logic, like if statusCode = 422 then ... <throw validation exception with known body type> else ... <throw general exception>

**Comment by SentryMan** [comment]
Oh yeah forgot I added that

**Comment by GeorgeSalu** [comment]
Thanks for the recommendation, I'll explore in the next few days
