### ISSUE TITLE
Unified metrics support for helidon and javalin

### ISSUE THREAD

**Issue by kprojectgr** [avaje/avaje-http#495]
I'm using the helidon generator and everything works as expected, but If I want to add metrics I need to manually intrument the Controller class in order to support for instance timers for each endpoint.

It would be great if we could use some sort of annotations in the generator in order to support automatic metric instrumentation.

**Comment by SentryMan** [comment]
I know [avaje-metrics](https://github.com/avaje/avaje-metrics) might have something like that, but that's the avaje lib I have the least experience with. (I use the OTEL/newrelic java agent mainly). @rbygrave would know more about it.

**Comment by rob-bygrave** [comment]
> automatic metric instrumentation.

avaje-metrics automatically instruments all `@Controller` (plus all "components" be they Spring Components, avaje-inject components [`@Singleton`, `@Component`] or JEE Components `@Stateless` etc. 

So this is how I do it. The docs are poor / outdated / need work.

I use avaje-metrics because it is a lot lighter than other metrics libs (Dropwizard, Micrometer etc), and so the "instrument ALL public methods of ALL components in the application" is completely acceptable [in terms of extra memory consumption and cpu overhead].

**Comment by kprojectgr** [comment]
Many Thanks!
